version: "3.1"

services:
  auth-db:
    container_name: auth-db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - auth-pg-volume:/var/lib/postgresql/data
    restart: always

  product-db:
    container_name: product-db
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - product-pg-volume:/var/lib/postgresql/data
    restart: always

  sales-db:
    container_name: sales-db
    image: mongo:7
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - sales-mongodb-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always

  sales-rabbit:
    container_name: sales-rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - sales-rabbit-volume:/data/db
    restart: always

volumes:
  product-pg-volume:

  auth-pg-volume:

  sales-mongodb-volume:

  sales-rabbit-volume: