version: "3.1"

services:
  auth-db:
    container_name: auth-db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - auth-pg-volume:/var/lib/postgresql/data
    restart: always
    networks:
      - sales_network
      
  product-db:
    container_name: product-db
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - product-pg-volume:/var/lib/postgresql/data
    restart: always
    networks:
      - sales_network

  sales-db:
    container_name: sales-db
    image: mongo:7
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - sales-mongodb-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - sales_network

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    hostname: sales_rabbit
    ports:
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - sales-rabbit-volume:/data/db
    environment:
      RABBIT_DEFAULT_USER: guest
      RABBIT_DEFAULT_PASS: guest
    restart: always
    networks:
      - sales_network

  auth-api:
    container_name: auth-api
    build: ./auth-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=container
      - PORT=8080
      - API_SECRET=YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=
      - DB_USER=admin
      - DB_NAME=auth-db
      - DB_PASSWORD=123456
      - DB_HOST=auth-db
      - DB_PORT=5433
    depends_on:
      - auth-db
    networks:
      - sales_network

  product-api:
    container_name: product-api
    build: ./product-api
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=container
      - PORT=8081
      - API_SECRET=YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=
      - DB_USER=admin
      - DB_NAME=product-db
      - DB_PASSWORD=123456
      - DB_HOST=product-db
      - DB_PORT=5432
      - RABBIT_MQ_HOST=sales-rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=8082
    depends_on:
      - product-db
      - sales-rabbit
    networks:
      - sales_network 

  sales-api:
    container_name: sales-api
    build: ./sales-api
    ports:
      - "8082:8082"
    depends_on:
      - sales-db
      - sales-rabbit
    networks:
      - sales_network
    environment:
      - NODE_ENV=container
      - PORT=8082
      - API_SECRET=YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=
      - MONGO_DB_URL=mongodb://admin:123456@sales-db:27017/sales
      - RABBIT_MQ_URL=amqp://guest:guest@sales-rabbit:5672/
      - PRODUCT_API_URL=http://product-api:8081/api/product


volumes:
  product-pg-volume:

  auth-pg-volume:

  sales-mongodb-volume:

  sales-rabbit-volume:

networks:
  sales_network:
    driver: bridge