version: '3.8'
services:
  auth-app:
    container_name: auth-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - auth-db

  auth-db:
    container_name: auth-db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: always
volumes:
  postgres-volume:
    external: true