version: '3.8'
services:
  product-app:
    container_name: product-app
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - product-db

  product-db:
    container_name: product-db
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: always
volumes:
  postgres-volume:
    external: true
